import { cookies } from "next/headers";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { FirebaseAuthListener } from "@/components/firebase-auth-listener";
import { getSession } from "@/lib/session/cookie";

import "./globals.css";

import { SessionStoreProvider } from "./_stores/session-store-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  const sessionIdToken = await getSession(cookies());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionStoreProvider initialState={{ idToken: sessionIdToken }}>
          <FirebaseAuthListener />

          {sessionIdToken === null ? auth : children}
        </SessionStoreProvider>
      </body>
    </html>
  );
}
